site_name: tstor
site_url: https://tstor.com/
repo_url: https://git.kmsign.ru/royalcat/tstor
repo_name: tstor/tstor

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Tutorials: tutorials.md
  - API Reference: api-reference.md

theme:
  logo: images/tstor_icon.png
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    primary: white
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.integrate

edit_uri: edit/master/mkdocs/docs/

plugins:
  - git-revision-date
  - search

extra:
  version:
    default: latest
    provider: mike

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
